version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    open-pull-requests-limit: 30
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: '@types/ioredis'
        versions:
          - '> 4.28.10'
