version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    open-pull-requests-limit: 30
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: 'p-retry'
        versions:
          - '>= 5.0.0'
      - dependency-name: 'pnpm'
        versions:
          - '> 7.5.2'
