version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    open-pull-requests-limit: 30
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: axios
        versions:
          - '> 0.27.2'
