version: '3'

services:

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    env_file: .env
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - $SERVER_PORT:$SERVER_PORT

  searcher:
    build:
      context: .
      dockerfile: ./searcher/Dockerfile
    env_file: .env
    init: true
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  resolver:
    build:
      context: .
      dockerfile: ./resolver/Dockerfile
    env_file: .env
    init: true
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  notifier:
    build:
      context: .
      dockerfile: ./notifier/Dockerfile
    env_file: .env
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    depends_on:
      - server
    ports:
      - $CLIENT_SERVER_PORT:3000

  db:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_DB=$DATABASE_NAME
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
    ports:
      - $DATABASE_PORT:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: bitnami/redis:6.2.6
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30

  datadog-agent:
    image: gcr.io/datadoghq/agent:7
    environment:
      - DD_API_KEY=$DD_API_KEY
      - DD_SITE=datadoghq.eu
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_CONTAINER_INCLUDE=name:resolver name:searcher name:server name:notifier
      - DD_CONTAINER_EXCLUDE=name:datadog-agent name:db name:redis
      - DD_ENABLE_PAYLOADS_EVENTS=false
      - DD_ENABLE_PAYLOADS_SERIES=false
      - DD_ENABLE_PAYLOADS_SERVICE_CHECKS=false
      - DD_ENABLE_PAYLOADS_SKETCHES=false
      - DD_APM_ENABLED=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /proc/:/host/proc/:ro
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro

volumes:
  redis_data:
    external: false
