version: '3'

services:
  server:
    build:
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./lib:/app/lib
      - ./node_modules:/app/node_modules
      - ./server:/app/server
    command: pnpm --filter @game-watch/server start:dev

  searcher:
    build:
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./lib:/app/lib
      - ./node_modules:/app/node_modules
      - ./searcher:/app/searcher
    command: pnpm --filter @game-watch/searcher start:dev

  resolver:
    build:
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./lib:/app/lib
      - ./node_modules:/app/node_modules
      - ./resolver:/app/resolver
    command: pnpm --filter @game-watch/resolver start:dev

  notifier:
    build:
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./lib:/app/lib
      - ./node_modules:/app/node_modules
      - ./notifier:/app/notifier
    command: pnpm --filter @game-watch/notifier start:dev

  # TODO: Not working
  client:
    build:
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./lib:/app/lib
      - ./node_modules:/app/node_modules
      - ./client:/app/client
      - ./client/.next/:/app/client/.next/
    command: pnpm --filter @game-watch/client start:dev
