version: '3'

services:
  db:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_DB=$DATABASE_NAME
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
    ports:
      - $DATABASE_PORT:5432

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=$DATABASE_USER
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - DATABASE_NAME=$DATABASE_NAME
      - SENTRY_ENVIRONMENT=$SENTRY_ENVIRONMENT
      - SENTRY_DSN=$SENTRY_DSN
      - SERVER_PORT=$SERVER_PORT
      - CORS_ORIGIN=$CORS_ORIGIN
    depends_on:
      - db
    ports:
      - $SERVER_PORT:$SERVER_PORT

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    depends_on:
      - server
    ports:
      - $CLIENT_SERVER_PORT:3000
