version: '3'

services:
  db:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_DB=$DATABASE_NAME
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
    ports:
      - $DATABASE_PORT:5432

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    env_file: .env
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    ports:
      - $SERVER_PORT:$SERVER_PORT

  searcher:
    build:
      context: .
      dockerfile: ./searcher/Dockerfile
    env_file: .env
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
  resolver:
    build:
      context: .
      dockerfile: ./resolver/Dockerfile
    env_file: .env
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis

  # Currently handled by vercel
  # client:
  #   build:
  #     context: .
  #     dockerfile: ./client/Dockerfile
  #   depends_on:
  #     - server
  #   ports:
  #     - $CLIENT_SERVER_PORT:3000

  redis:
    image: bitnami/redis:6.2.6
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
    ports:
      - 6379:6379
